USE ucode_web;

CREATE TABLE IF NOT EXISTS powers (
    id INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    hero_id INT UNSIGNED NOT NULL,
    name TEXT NOT NULL,
    power_points INT NOT NULL,
    type ENUM('attack', 'defence') NOT NULL,
    FOREIGN KEY (hero_id) REFERENCES heroes(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS races (
    id INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    hero_id INT UNSIGNED NOT NULL,
    name TEXT NOT NULL,
    FOREIGN KEY (hero_id) REFERENCES heroes(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS teams (
    id INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    hero_id INT UNSIGNED NOT NULL,
    name TEXT NOT NULL,
    FOREIGN KEY (hero_id) REFERENCES heroes(id) ON DELETE CASCADE
);
