export const cardData = {
  tank_1: {
    name: 'F4U-1D',
    nation: 'usa/',
    attack: 8,
    def: 2,
    diesel: 1,
    move: 1,
  },
  tank_2: {
    name: 'M4A2',
    nation: 'usa/',
    attack: 4,
    def: 8,
    diesel: 1,
    move: 1,
  },
  tank_3: {
    name: 'M5A1',
    nation: 'usa/',
    attack: 2,
    def: 1,
    diesel: 1,
    move: 1,
  },
  tank_4: {
    name: 'M8A1',
    nation: 'usa/',
    attack: 4,
    def: 7,
    diesel: 5,
    move: 1,
  },
  tank_5: {
    name: 'M10_GMC',
    nation: 'usa/',
    attack: 6,
    def: 1,
    diesel: 1,
    move: 1,
  },
  tank_6: {
    name: 'M42',
    nation: 'usa/',
    attack: 6,
    def: 4,
    diesel: 4,

    move: 1,
  },
  tank_7: {
    name: 'M56',
    nation: 'usa/',
    attack: 5,
    def: 1,
    diesel: 2,
    move: 1,
  },
  tank_8: {
    name: 'T29',
    nation: 'usa/',
    attack: 5,
    def: 10,
    diesel: 7,
    move: 1,
  },
  tank_9: {
    name: 'Fw190A-1',
    nation: 'German/',
    attack: 5,
    def: 10,
    diesel: 7,
    move: 1,
  },
  tank_10: {
    name: 'herzer',
    nation: 'German/',
    attack: 5,
    def: 10,
    diesel: 7,
    move: 1,
  },
  tank_11: {
    name: 'Ju88A-4',
    nation: 'German/',
    attack: 5,
    def: 10,
    diesel: 7,
    move: 1,
  },
  tank_12: {
    name: 'Pantera2',
    nation: 'German/',
    attack: 5,
    def: 10,
    diesel: 7,
    move: 1,
  },
  tank_13: {
    name: 'Pz3',
    nation: 'German/',
    attack: 5,
    def: 10,
    diesel: 7,
    move: 1,
  },
  tank_14: {
    name: 'Pz4',
    nation: 'German/',
    attack: 5,
    def: 10,
    diesel: 7,
    move: 1,
  },
  tank_15: {
    name: 'tiger1',
    nation: 'German/',
    attack: 5,
    def: 10,
    diesel: 7,
    move: 1,
  },
  tank_16: {
    name: 'tiger2',
    nation: 'German/',
    attack: 5,
    def: 10,
    diesel: 7,
    move: 1,
  },
  tank_17: {
    name: 'Bm-0',
    nation: 'Sssr/',
    attack: 5,
    def: 10,
    diesel: 7,
    move: 1,
  },
  tank_18: {
    name: 'BT-5',
    nation: 'Sssr/',
    attack: 5,
    def: 10,
    diesel: 7,
    move: 1,
  },
  tank_19: {
    name: 'IS-1',
    nation: 'Sssr/',
    attack: 5,
    def: 10,
    diesel: 7,
    move: 1,
  },
  tank_20: {
    name: 'IS-2',
    nation: 'Sssr/',
    attack: 5,
    def: 10,
    diesel: 7,
    move: 1,
  },
  tank_21: {
    name: 'Isy-1',
    nation: 'Sssr/',
    attack: 5,
    def: 10,
    diesel: 7,
    move: 1,
  },
  tank_22: {
    name: 'KV-1',
    nation: 'Sssr/',
    attack: 5,
    def: 10,
    diesel: 7,
    move: 1,
  },
  tank_23: {
    name: 'T-34',
    nation: 'Sssr/',
    attack: 5,
    def: 10,
    diesel: 7,
    move: 1,
  },
  tank_24: {
    name: 'Yk-9',
    nation: 'Sssr/',
    attack: 5,
    def: 10,
    diesel: 7,
    move: 1,
  },
  tank_25: {
    name: 'Zis-3',
    nation: 'Sssr/',
    attack: 5,
    def: 10,
    diesel: 7,
    move: 1,
  },
};
